plugins {
    id 'org.jetbrains.kotlin.jvm' version '2.3.20'
    id 'org.jetbrains.compose' version '1.10.3'
    id 'org.jetbrains.kotlin.plugin.compose' version '2.3.20'
}

kotlin {
    jvmToolchain(21)
}

dependencies {
    implementation project(':Shared')
    implementation 'org.json:json:20240303'
    implementation compose.desktop.currentOs
    implementation 'org.jetbrains.compose.material3:material3:1.10.0-alpha05'
    implementation 'org.jetbrains.kotlinx:kotlinx-coroutines-core:1.10.2'
    testImplementation 'junit:junit:4.13.2'
}

compose.desktop {
    application {
        mainClass = 'org.firstinspires.ftc.mockrobot.MockRobotMainKt'
        jvmArgs(
            '-Dfile.encoding=UTF-8',
            '--enable-native-access=ALL-UNNAMED'
        )
    }
}
